### ISSUE TITLE
ConstantRange incorrectly converted to ConstantIntValue

### ISSUE THREAD

**Issue by Sinhika** [SizableShrimp/Forge-Class-Remapper#4]
"import net.minecraft.loot.ConstantRange" (1.16) should become "import net.minecraft.world.level.storage.loot.providers.number.ConstantValue"; unfortunately, you converted it to "ConstantIntValue", which doesn't exist in Minecraft and greatly confused my IDE, which thought it was from the sun.jvm package.

**Comment by SizableShrimp** [comment]
The script only remaps to Mojmaps based on what Minecraft version you start with as that is how it is designed. In 1.16.5, the class is in fact called `ConstantIntValue` in mojmaps, which is correct. The script does not deal with class renames across versions, so this is not a bug with the script.
