### ISSUE TITLE
"No service of type JavaToolchainService available in ProjectScopeServices."

### ISSUE THREAD

**Issue by uSkizzik** [SizableShrimp/Forge-Class-Remapper#8]
I don't know if this really deserves a whole issue but here I go.
So, basically, I'm backporting my mod from 1.17 to 1.16 and I followed the steps in the readme.
I changed the ForgeGradle to 4.1.+ and my gradle to 6.8.1. After that I changed my JavaLanguageVersion to 8 and my SDK in Project Structure. I also added the script under all plugins (like it says).
Here comes the issue. When I run `gradlew -PUPDATE_CLASSNAMES=true -PREVERSED=true updateClassnames`, it starts off normally and then it fails with the following issue:
```
* Where:
Script 'https://raw.githubusercontent.com/SizableShrimp/Forge-Class-Remapper/main/classremapper.gradle' line: 49

* What went wrong:
A problem occurred configuring root project 'Mod Files'.
> Could not create task ':extractRangeMap'.
   > Could not create task of type 'ExtractRangeMap'.
      > No service of type JavaToolchainService available in ProjectScopeServices.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
I read something about it in a gradle issue which said it's fixed in gradle 7 but I doubt I need to upgrade since after all I used this script to update to 1.17.

**Comment by SizableShrimp** [comment]
This is not a bug with the script. This is user error. You MUST run the script with FG 5 and Gradle 7 or it will fail. You can use FG5 for 1.16 perfectly fine. Or, at least change it after running this script.
